version: "3.3"


services:
  app:
    build: .
    volumes:
      - ./:/project_02

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - app
